### ISSUE TITLE
Error decoding a value of Double.max

### ISSUE THREAD

**Issue by richardgroves** [asensei/AnyCodable#9]
With a source JSON string of:

{"params":{"timeLeft":1.7976931348623157e+308}}

I get an error at line 67 of AnyCodable.swift - console log show:

Fatal error: Double value cannot be converted to Int because the result would be greater than Int.max: file /Library/Caches/com.apple.xbs/Binaries/SwiftPrebuiltSDKModules_macOS/install/TempContent/Objects/EmbeddedProjects/CrossTrain_macOS_SDK/macOS_SDK/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/swift/Swift.swiftmodule/x86_64.swiftinterface, line 29404

There seems to be implied that if `value.rounded()` returns a value then it can be cast to an `Int` - but obviously there are a lot of `Double` values that are outside the range of `Int`

**Comment by valeriomazzeo** [comment]
Hi @richardgroves, thanks for your feedback.

Unfortunately, this repository is no longer maintained. It was meant as an experiment to explore if it was possible to make Codable works with undefined data structures.

We came  to the conclusion that there are too many edge cases, and we have since then completely moved away from fuzzy decoding of `Any` types.

For JSON in particular, I suggest you create your own `JSON: Codable` type - if you want to use  Codable and don't know your JSON structure, nor want to use `JSONSerialization`.

You may find this useful https://gist.github.com/valeriomazzeo/28c996ae9e6cd95456a3687b40edc5d6

**Comment by richardgroves** [comment]
@valeriomazzeo Thanks! You might want to put a notice on the README about this being legacy.

For the tiny command line debug tool I'm working on a quick fork and patch of the Int() cast has worked - but thanks for the link to the GIST - that looks like it could be handy if I need this sort of thing again in a live project.
